blank_issues_enabled: false
contact_links:
  - name: 社区讨论 | GitHub Community Support
    url: https://github.com/yatengLG/ISAT_with_segment_anything/discussions
    about: 讨论和回答问题，请在社区进行 | Please ask and answer questions here.

